import * as FileSystem from "expo-file-system/legacy";
import { router } from "expo-router";
import * as Sharing from "expo-sharing";
import { useRef, useState } from "react";
import {
  Alert,
  Animated,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { supabase } from "../../lib/supabase";
import { useTheme } from "../../lib/ThemeContext";

export default function SettingsScreen() {
  const { isDark, toggleDark, colors } = useTheme();
  const animatedValue = useRef(new Animated.Value(isDark ? 1 : 0)).current;
  const [exporting, setExporting] = useState(false);

  const handleToggle = () => {
    const toValue = isDark ? 0 : 1;
    Animated.timing(animatedValue, {
      toValue,
      duration: 400,
      useNativeDriver: false,
    }).start();
    toggleDark();
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    router.replace("/login");
  };

  const handleExport = async () => {
    setExporting(true);
    try {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) return;

      const isAdmin = user.email === "admin@test.com";

      // Fetch tasks — admin gets all, user gets their own
      const query = supabase
        .from("tasks")
        .select("*")
        .order("created_at", { ascending: false });

      const { data: tasks, error } = isAdmin
        ? await query
        : await query.eq("user_id", user.id);

      if (error) throw error;
      if (!tasks || tasks.length === 0) {
        Alert.alert("No Tasks", "You have no tasks to export.");
        setExporting(false);
        return;
      }

      // Fetch profiles for admin to resolve names
      let profileMap: { [key: string]: string } = {};
      if (isAdmin) {
        const { data: profiles } = await supabase
          .from("profiles")
          .select("id, full_name, email");
        if (profiles) {
          profiles.forEach((p: any) => {
            profileMap[p.id] =
              p.full_name || p.email?.split("@")[0] || "Unknown";
          });
        }
      }

      // Build text summary
      const now = new Date().toLocaleDateString();
      const pending = tasks.filter((t) => !t.completed);
      const completed = tasks.filter((t) => t.completed);

      let text = `TASK REPORT — ${now}\n`;
      text += `${"=".repeat(40)}\n\n`;
      text += `Total: ${tasks.length} | Pending: ${pending.length} | Completed: ${completed.length}\n\n`;

      if (pending.length > 0) {
        text += `PENDING TASKS (${pending.length})\n`;
        text += `${"-".repeat(30)}\n`;
        pending.forEach((t, i) => {
          text += `${i + 1}. ${t.title}\n`;
          if (t.priority) text += `   Priority: ${t.priority}\n`;
          if (t.category) text += `   Category: ${t.category}\n`;
          if (t.due_date)
            text += `   Due: ${new Date(t.due_date).toLocaleDateString()}\n`;
          if (isAdmin && profileMap[t.user_id])
            text += `   Assigned to: ${profileMap[t.user_id]}\n`;
          text += "\n";
        });
      }

      if (completed.length > 0) {
        text += `COMPLETED TASKS (${completed.length})\n`;
        text += `${"-".repeat(30)}\n`;
        completed.forEach((t, i) => {
          text += `${i + 1}. ${t.title}\n`;
          if (t.completed_at)
            text += `   Completed: ${new Date(t.completed_at).toLocaleDateString()}\n`;
          if (isAdmin && profileMap[t.user_id])
            text += `   Assigned to: ${profileMap[t.user_id]}\n`;
          text += "\n";
        });
      }

      text += `${"=".repeat(40)}\n`;
      text += `Generated by Task Manager\n`;

      // Try native share sheet first (works without file system)
      const canShare = await Sharing.isAvailableAsync();

      if (canShare) {
        // Write to a temp file and share it
        const fileUri =
          FileSystem.documentDirectory + `tasks_${Date.now()}.txt`;
        await FileSystem.writeAsStringAsync(fileUri, text, {
          encoding: "utf8",
        });
        await Sharing.shareAsync(fileUri, {
          mimeType: "text/plain",
          dialogTitle: "Share Task Report",
          UTI: "public.plain-text",
        });
      } else {
        // Fallback to React Native's built-in Share (no file, just text)
        await Share.share({
          message: text,
          title: "Task Report",
        });
      }
    } catch (e: any) {
      console.log("Export error:", e);
      Alert.alert("Error", "Something went wrong exporting your tasks.");
    }
    setExporting(false);
  };

  const toggleBackground = animatedValue.interpolate({
    inputRange: [0, 1],
    outputRange: ["#ddd", "#6200ee"],
  });

  const knobPosition = animatedValue.interpolate({
    inputRange: [0, 1],
    outputRange: [2, 22],
  });

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <Text style={[styles.title, { color: colors.text }]}>Settings</Text>

      <TouchableOpacity
        style={[styles.card, { backgroundColor: colors.card }]}
        onPress={() => router.push("/profile")}
      >
        <Text style={[styles.settingLabel, { color: colors.text }]}>
          Profile
        </Text>
        <Text style={[styles.chevron, { color: colors.subtext }]}>›</Text>
      </TouchableOpacity>

      <TouchableOpacity
        style={[styles.card, { backgroundColor: colors.card }]}
        onPress={handleExport}
        disabled={exporting}
      >
        <Text style={[styles.settingLabel, { color: colors.text }]}>
          {exporting ? "Exporting..." : "Export & Share Tasks"}
        </Text>
        <Text style={[styles.chevron, { color: colors.subtext }]}>›</Text>
      </TouchableOpacity>

      <View style={[styles.card, { backgroundColor: colors.card }]}>
        <Text style={[styles.settingLabel, { color: colors.text }]}>
          Dark Mode
        </Text>
        <TouchableOpacity onPress={handleToggle}>
          <Animated.View
            style={[styles.toggle, { backgroundColor: toggleBackground }]}
          >
            <Animated.View
              style={[
                styles.knob,
                { transform: [{ translateX: knobPosition }] },
              ]}
            />
          </Animated.View>
        </TouchableOpacity>
      </View>

      <Text style={[styles.hint, { color: colors.subtext }]}>
        {isDark ? "Dark mode is on" : "Light mode is on"}
      </Text>

      <TouchableOpacity style={styles.logoutButton} onPress={handleLogout}>
        <Text style={styles.logoutText}>Logout</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 60,
    paddingHorizontal: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 32,
  },
  card: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: "600",
  },
  chevron: {
    fontSize: 22,
    fontWeight: "600",
  },
  toggle: {
    width: 50,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    padding: 2,
  },
  knob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#fff",
  },
  hint: {
    fontSize: 14,
    textAlign: "center",
    marginTop: 8,
    marginBottom: 32,
  },
  logoutButton: {
    backgroundColor: "#ffebee",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 16,
  },
  logoutText: {
    color: "#c62828",
    fontSize: 16,
    fontWeight: "bold",
  },
});
